## Two dimensional (matrix)

In [1]:
import numpy as np

In [2]:
sample_matrix=np.array([50,20,13],[24,23,41],[21,33,9])
sample_matrix

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [3]:
sample_matrix=np.array(([50,20,13],[24,23,41],[21,33,9]))
sample_matrix

array([[50, 20, 13],
       [24, 23, 41],
       [21, 33,  9]])

In [4]:
sample_matrix[1,2]

41

In [5]:
sample_matrix[2,:]

array([21, 33,  9])

In [8]:
sample_matrix[:,1]

array([20, 23, 33])

In [9]:
sample_matrix[2]

array([21, 33,  9])

In [11]:
sample_matrix[:,(1,2)]

array([[20, 13],
       [23, 41],
       [33,  9]])

### selection Technique

In [13]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
sample_array+sample_array  ### 1+1,2+2,3+3.....19+19

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [15]:
np.exp(sample_array) ### exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [16]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [17]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [18]:
np.max(sample_array)

19

In [19]:
np.min(sample_array)

1

In [20]:
np.argmax(sample_array)

18

In [21]:
np.argmin(sample_array)

0

In [22]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [23]:
np.std(sample_array)

5.477225575051661

In [24]:
np.var(sample_array)

30.0

In [25]:
np.mean(sample_array)

10.0

In [26]:
array=np.random.rand(3,4)
array

array([[0.26079626, 0.87654684, 0.55603605, 0.74427179],
       [0.72688028, 0.35454682, 0.02098703, 0.19832343],
       [0.91352495, 0.53837454, 0.09139097, 0.25610629]])

In [27]:
np.round(array,decimals=2)

array([[0.26, 0.88, 0.56, 0.74],
       [0.73, 0.35, 0.02, 0.2 ],
       [0.91, 0.54, 0.09, 0.26]])

In [28]:
sports=np.array(['golf','cricket','fball','vball','cricket'])
sports

array(['golf', 'cricket', 'fball', 'vball', 'cricket'], dtype='<U7')

In [29]:
sports=np.array(['golf','cricket','fball','vball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf', 'vball'], dtype='<U7')